apiVersion: v1
kind: Pod
metadata:
  name: peekaboo
spec:
  containers:
    - name: peekaboo
      image: arniinaba/peekaboo:0.0.3
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date); sleep 10;done"]